RoR - Migrate to Rails PR
sasaranAndrei/RoR_assignment3 pull request #1
Opened 2021-04-28 12:07 UTC by sasaranAndrei

This Pull Request is made for the third assignment of Wofpack Digital RoR Internship.

Made changes include:

- Migrate site to Rails
- Use SCSS & HAML for stylesheets
- Deploy on Heroku
- Store the data in the DataBase
- Create & Read operations on Product

For my next update I will implement:

- Update & Delete operations on Product
- Active Storage for Images

2021-04-28 14:45 UTC, vaneaclaudia requested changes

2021-04-28 14:45 UTC, vaneaclaudia commented on app/controllers/product_controller.rb
> +    redirect_to products_path
It seems that you don't use the `product` variable here so maybe you can just have `Product.create(product_params)` ?

2021-04-28 14:45 UTC, vaneaclaudia commented on config/routes.rb
> +  get 'product/delete'
do you need these get endpoints here? you have `resources :products` below which will define the endpoints for you. 

More details here:

<img width="704" alt="Screenshot 2021-04-28 at 17 44 33" src="https://user-images.githubusercontent.com/70625532/116423526-6f668200-a849-11eb-8dfc-42b347ac95ef.png">

2021-05-03 20:32 UTC, sasaranAndrei commented
Made changes include:
- Add CRUD operations
- Loading Products from DB
- Load images from Local Storage

For my next update I will:
- Load images from Active Storage
- Refactor the code

2021-05-04 10:26 UTC, sasaranAndrei commented
@vaneaclaudia

2021-05-05 06:44 UTC, vaneaclaudia requested changes

2021-05-05 06:44 UTC, vaneaclaudia commented on app/controllers/products_controller.rb
> +    Product.create(product_params)
will this save the picture also?

2021-05-05 06:44 UTC, vaneaclaudia commented on app/controllers/products_controller.rb
> +    redirect_to products_path
what will happen if create will fail? should you maybe display an error message and not redirect?

2021-05-05 06:44 UTC, vaneaclaudia commented on app/controllers/products_controller.rb
> +    @product.update(product_params)
same remark as for `create` method

2021-05-05 06:44 UTC, vaneaclaudia commented on config/cloudinary.yml
> +  api_secret: ZIbGl7lULuQlx8Y4WgQhjzfQ6ao
the secrets should not be committed to the repo, instead you should use environment variables (via dotenv gem) or use Rails credentials

2021-05-05 06:44 UTC, vaneaclaudia commented on db/migrate/20210428101853_create_products.rb
> +
you can also add `null` constraints when creating tables if needed like this:

`t.string :title, null: false`

2021-05-05 06:44 UTC, vaneaclaudia commented on test/controllers/products_controller_test.rb
> +  test "should get show" do
you can update the test files to use single quotes instead of double quotes where you don't have interpolation

2021-05-06 14:23 UTC, chioreandan approved these changes

2021-05-06 14:23 UTC, chioreandan commented on Gemfile
> +  gem 'dotenv-rails'
add gem versions

2021-05-06 14:23 UTC, chioreandan commented on app/assets/stylesheets/pages.scss
> +}
this indentation looks a bit off to me

2021-05-06 14:23 UTC, chioreandan commented on app/controllers/products_controller.rb
> +
no need for this empty line

2021-05-06 14:23 UTC, chioreandan commented on app/javascript/packs/animation.js
> +}
do you still need this?

2021-05-06 14:23 UTC, chioreandan commented on app/javascript/packs/animation.js
> +  foodContainer.appendChild(newItem);
you can remove the comments

2021-05-06 14:23 UTC, chioreandan commented on db/seeds.rb
> +Product.create(title: 'Item Seven', description: 'Second courses', price: 120.00)
you can use the example from above for multiple seeds for the same model:
```movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])```

2021-05-06 14:24 UTC, chioreandan requested changes
Please review the request changes from above

2021-05-07 10:51 UTC, sasaranAndrei commented
I refactored my code with all the requested changes

2021-05-07 10:54 UTC, vaneaclaudia approved these changes

2021-05-07 10:55 UTC, merged