RoR - Remember Me PR
sasaranAndrei/RoR_assignment3 pull request #3
Opened 2021-05-17 10:30 UTC by sasaranAndrei

This Pull Request is made for the fifth assignment of Wofpack Digital RoR Internship.

Made changes include:

    Add Remember me functionality
    Add to Cart styling
    Deploy on Heroku -> here (with images from Cloudinary)
    Hiding private information with dotenv gem

For my next update I will implement:

- Tests to validate that an unauthorized user can't add a product to the cart

2021-05-17 12:41 UTC, flaviuvr requested changes

2021-05-17 12:41 UTC, flaviuvr commented on app/views/pages/index.html.haml
> +                = cl_image_tag(product.picture.key, :class => 'food-img') if product.picture.attached?
If you display the images from cloudinary, it would be a good idea to remove them from the assets folder.

2021-05-17 12:41 UTC, flaviuvr commented on app/views/pages/index.html.haml
>                %span.item-group= product.description
You can improve readability here by placing the content on a new line, like this:
```suggestion
              %span.item-name
                = product.title
              %span.item-group
                = product.description
```

2021-05-17 12:41 UTC, flaviuvr commented on app/views/products/new.html.haml
>    = form.submit
Also, for better readability, you can group the related fields by leaving empty lines around them, like so:
`
= form.text_field :title, placeholder: 'title'  

= form.text_field :description, placeholder: 'description'  

= form.number_field :price, placeholder: 'price'  

= form.file_field :picture  
= form.file_field :picture, direct_upload: true  

= form.submit`

2021-05-17 12:41 UTC, flaviuvr commented on spec/rails_helper.rb
> +# If you are not using ActiveRecord, you can remove these lines.
You probably don't need these comments. You can delete them also on the rest of the generated files.

2021-05-17 12:41 UTC, flaviuvr commented on app/controllers/users_controller.rb
>        flash[:success] = 'Welcome to our restaurant!'
I can't see this rendering anything when testing on heroku.🤔 Maybe you could keep it and implement the flash later but for now I don't think is necessary.

2021-05-17 12:41 UTC, flaviuvr commented on app/views/pages/index.html.haml
> +            %input#slider{:max => '135', :min => '0', :oninput => 'sliderChange()', :steps => '1', :type => 'range', :value => '135'}/
Nice one!🤟

2021-05-17 15:51 UTC, firte07 requested changes
You need to pay more attention on small details, but overall a very good job :D

2021-05-17 15:51 UTC, firte07 commented on Gemfile
>  gem 'haml-rails', '~> 2.0'
You can indent a little bit here. It looks better if you put all the versions on the same column. Also, is more readable.

2021-05-17 15:51 UTC, firte07 commented on config/cloudinary.yml
> +production:
You can add an empty line before the `production`

2021-05-17 15:51 UTC, firte07 commented on config/cloudinary.yml
> +test:
Also before the `test:`

2021-05-17 15:51 UTC, firte07 commented on spec/spec_helper.rb
> +# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
There are a lot of comments here. If you do not need them, you should delete then.

2021-05-18 10:54 UTC, flaviuvr approved these changes
Nice work, keep it up!👌

2021-05-18 15:54 UTC, firte07 approved these changes
From my point of view, everything is fine! Nice work!

2021-05-18 15:54 UTC, firte07 commented on Gemfile
> +gem 'bootsnap',     '>= 1.4.4', require: false
This looks so nice and clean!

2021-05-19 07:28 UTC, VictorMotogna approved these changes

2021-05-20 06:52 UTC, merged